### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by trashfloozy** [CompSciOrBust/JCToolBox#1]
I get the following error when I attempt to compile this and don't really know why.

https://pasteboard.co/J0osUDZ.png

**Comment by CompSciOrBust** [comment]
On line 13 change size_t to s32 . LibNX changed one of the data types in hidsysGetUniquePadsFromNpad since I last updated this repo. I want to work some more on this soon but I have two local branches, one with a half broken gui and one with a config file support so I need to combine them first (development is a lot slower because my switch broke so I have no actual hardware to test on).

**Comment by trashfloozy** [comment]
Thank you :) I would actually be willing to test, even if I can't back up my JoyCons since I could just replace them.

**Comment by CompSciOrBust** [comment]
Thanks. You shouldn't need a back up for this anyway because it's using debug functions built in to the switch os. If you have discord join my server (it's linked on the read me file for Amiigo and N-Xplorer) and I'll give you the tester role.
